#!/bin/sh

RES=$(python3 /home/workshop/pasta/mark.py)
. /etc/environment
curl -X POST -u "$PLATFORM_USERNAME:$PLATFORM_PASSWORD" -H "Content-Type: application/json" -d "{\"token\": \"$ATTEMPT_TOKEN\",\"result\":$RES}" traefik.platform/api/v1/platform/attempt/submit
